Dz 07 04 input
js-tasks-ru/htmlcss-20210812_mediaca pull request #18
Opened 2021-09-06 06:06 UTC by mediaca

2021-09-06 06:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-06 12:19 UTC, GSemikozov requested changes

2021-09-06 12:19 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    padding-right: 5rem;
лучше этот паддинг пусть всегда будет таким, а не только при таком статусе

2021-09-06 12:19 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    fill: none;
стили для иконки лучше описать сразу, вне зависимости от статуса, а при изменении статуса - просто отображать нужную иконку

2021-09-06 18:31 UTC, mediaca commented on 07-lection5/04-input/input.css
> +    padding-right: 5rem;
согласен, поправил

2021-09-06 18:31 UTC, mediaca commented on 07-lection5/04-input/input.css
> +    fill: none;
поправил

2021-09-06 18:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-06 18:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-07 18:04 UTC, GSemikozov approved these changes

2021-09-07 18:04 UTC, merged